import ooo_pkg::*;

// Reorder buffer for precise, in-order retirement.
//
// Owner: Mike
// Independent after ooo_pkg.sv: yes
//
// Dispatch allocates one tail entry. Results may complete entries out of
// order, but only a complete head entry may retire. Recovery removes entries
// younger than the resolving branch and moves the tail behind that branch.

module rob (
    input logic clk,
    input logic rst,

    // Single-wide allocation. dispatch_tag_o is the tag rename must place in
    // dispatch_uop_i before the transfer is accepted.
    input  logic         dispatch_valid_i,
    input  var renamed_uop_t dispatch_uop_i,
    output logic         dispatch_ready_o,
    output rob_tag_t     dispatch_tag_o,

    // One completion per cycle from the common result bus.
    input var result_bus_t result_i,

    // Selective branch recovery.
    input var recovery_event_t recovery_i,
    input logic flush_all_i,

    // In-order head interface. The ROB advances only on valid && ready.
    output logic        commit_valid_o,
    output var rob_commit_t commit_o,
    input  logic        commit_ready_i,

    // Age reference used by issue and memory queues.
    output rob_tag_t head_tag_o,
    output logic     empty_o,
    output logic     full_o,
    output logic [ROB_INDEX_BITS:0] count_o
);

    rob_entry_t entries_q [0:ROB_ENTRIES-1];
    rob_tag_t head_tag_q;
    rob_tag_t tail_tag_q;
    logic [ROB_INDEX_BITS:0] count_q;

    logic dispatch_fire;
    logic commit_fire;

    function automatic rob_entry_t make_dispatch_entry(
        input renamed_uop_t uop,
        input rob_tag_t tag
    );
        rob_entry_t entry;

        entry = ROB_ENTRY_EMPTY;
        entry.valid = 1'b1;
        // Decode-time exceptions and halt instructions need no execution
        // result before they can reach precise retirement.
        entry.complete = uop.decoded.exception_valid || uop.decoded.halt;
        entry.rob_tag = tag;
        entry.pc = uop.decoded.pc;
        entry.instruction = uop.decoded.instruction;
        entry.uop_class = uop.decoded.uop_class;
        entry.writes_rd = uop.has_phys_destination;
        entry.rd_arch = uop.decoded.rd_arch;
        entry.rd_phys = uop.rd_phys;
        entry.stale_rd_phys = uop.stale_rd_phys;
        entry.mem_size = uop.decoded.mem_size;
        entry.load_unsigned = uop.decoded.load_unsigned;
        entry.halt = uop.decoded.halt;
        entry.exception_valid = uop.decoded.exception_valid;
        entry.exception_cause = uop.decoded.exception_cause;
        entry.exception_value = uop.decoded.exception_value;
        return entry;
    endfunction

    always_comb begin
        empty_o = (count_q == 0);
        full_o = (count_q == ROB_ENTRIES);
        count_o = count_q;

        // Recovery owns this cycle. Suppress external handshakes that the
        // recovery state update intentionally does not consume.
        dispatch_ready_o = !full_o && !recovery_i.valid && !flush_all_i;
        dispatch_tag_o = tail_tag_q;
        head_tag_o = head_tag_q;

        commit_o = ROB_ENTRY_EMPTY;
        if (!empty_o)
            commit_o = entries_q[rob_index(head_tag_q)];

        // A precise trap or halt is generated by this head entry. Do not gate
        // commit_valid_o with flush_all_i, or the head deasserts the flush
        // that it just requested and creates a combinational control loop.
        commit_valid_o = !empty_o && commit_o.valid && commit_o.complete &&
                         !recovery_i.valid;
        dispatch_fire = dispatch_valid_i && dispatch_ready_o;
        commit_fire = commit_valid_o && commit_ready_i;
    end

    always_ff @(posedge clk) begin : rob_state
        integer survivor_count;
        rob_index_t result_index;
        logic recovery_tag_found;

        if (rst) begin
            for (int index = 0; index < ROB_ENTRIES; index++)
                entries_q[index] <= ROB_ENTRY_EMPTY;

            head_tag_q <= '0;
            tail_tag_q <= '0;
            count_q <= '0;
        end else if (flush_all_i) begin
            for (int index = 0; index < ROB_ENTRIES; index++)
                entries_q[index] <= ROB_ENTRY_EMPTY;
            head_tag_q <= rob_recovery_next_tag(head_tag_q);
            tail_tag_q <= rob_recovery_next_tag(head_tag_q);
            count_q <= '0;
        end else begin
            // A result may complete any live slot, but only when the entire
            // position-plus-generation tag matches. Ignore duplicate results
            // after an entry is already complete so a stalled head is stable.
            result_index = rob_index(result_i.rob_tag);
            if (result_i.valid && entries_q[result_index].valid &&
                !entries_q[result_index].complete &&
                (entries_q[result_index].rob_tag == result_i.rob_tag)) begin
                entries_q[result_index].complete <= 1'b1;
                entries_q[result_index].result <= result_i.result;
                entries_q[result_index].memory_address_valid <=
                    result_i.memory_address_valid;
                entries_q[result_index].memory_address <=
                    result_i.memory_address;
                entries_q[result_index].store_data <= result_i.store_data;

                if (result_i.branch_valid) begin
                    entries_q[result_index].branch_taken <=
                        result_i.branch_taken;
                    entries_q[result_index].branch_target <=
                        result_i.branch_target;
                end

                if (result_i.exception_valid) begin
                    entries_q[result_index].exception_valid <= 1'b1;
                    entries_q[result_index].exception_cause <=
                        result_i.exception_cause;
                    entries_q[result_index].exception_value <=
                        result_i.exception_value;
                end
            end

            if (recovery_i.valid) begin
                recovery_tag_found =
                    entries_q[rob_index(recovery_i.branch_tag)].valid &&
                    (entries_q[rob_index(recovery_i.branch_tag)].rob_tag ==
                     recovery_i.branch_tag);

                if (recovery_tag_found) begin
                    for (int index = 0; index < ROB_ENTRIES; index++) begin
                        if (entries_q[index].valid &&
                            rob_is_younger(entries_q[index].rob_tag,
                                           recovery_i.branch_tag,
                                           head_tag_q)) begin
                            entries_q[index] <= ROB_ENTRY_EMPTY;
                        end
                    end

                    survivor_count =
                        (int'(recovery_i.branch_tag.position) -
                         int'(head_tag_q.position) + (2 * ROB_ENTRIES)) %
                        (2 * ROB_ENTRIES) + 1;
                    count_q <= survivor_count;
                    tail_tag_q <= rob_recovery_next_tag(recovery_i.branch_tag);
                end
            end else begin
                if (commit_fire) begin
                    entries_q[rob_index(head_tag_q)] <= ROB_ENTRY_EMPTY;
                    head_tag_q <= rob_next_tag(head_tag_q);
                end

                if (dispatch_fire) begin
                    entries_q[rob_index(tail_tag_q)] <=
                        make_dispatch_entry(dispatch_uop_i, tail_tag_q);
                    tail_tag_q <= rob_next_tag(tail_tag_q);
                end

                case ({dispatch_fire, commit_fire})
                    2'b01: count_q <= count_q - 1'b1;
                    2'b10: count_q <= count_q + 1'b1;
                    default: count_q <= count_q;
                endcase
            end
        end
    end

endmodule
